# autogit.yaml - Git 自动同步配置

repos:
  - path: /data/manjaro/0Manjaro
    branch: main
  - path: /data/manjaro/manjaro_kde_conf
    branch: main
  - path: /data/manjaro/manjaro_basic_conf
    branch: main
  - path: /data/manjaro/manjaro_software_conf
    branch: main

commit_msg: "Auto sync"
